library(stringr)
library(gplots)
library(XML)
library(vcd,vcdExtra)
library(reporttools)
library(Hmisc)
library(etable)
setwd(dir="~/Desktop/Liemannen")
####### Clean up the main dataset                             #####################  
Patients <-read.csv(file="Stroke_Patients.csv",header=TRUE,sep=",")
Patients$DOB <-as.Date(Patients$DOB,format="%d/%m/%Y")
Patients$Date_Stroke<-as.Date(Patients$Date_Stroke,format="%d/%m/%Y")
Patients$DateAssessed <-as.Date(Patients$DateAssessed,format="%y/%m/%d",origin=01/01/2000)
Patients$Date_Treated <-as.Date(Patients$Date_Treated,format="%d/%m/%Y")
Patients$Date_Asst1 <-as.Date(Patients$Date_Asst1,format="%d/%m/%Y")
Patients$Date_Asst2 <-as.Date(Patients$Date_Asst2,format="%d/%m/%Y")
Patients$Speed_Change <-Patients$Speed_Asst2 - Patients$Speed_Asst1
Tab <- tabular.ade(x_vars='Age', rows=c('sex',"Surgery"), rnames=c('Sex',"Surgery"), data=Patients, FUN=mean_sd_cell)
print(xtable(Tab, caption='Median (SD) of Age'), include.rownames=F,include.colnames=F, caption.placement="top")
Tab <- tabular.ade(x_vars='Speed_Change', rows=c("sex","Surgery"), rnames=c('Sex',"Surgery"), data=Patients, FUN=mean_sd_cell)
print(xtable(Tab, caption='Median Increase (SD) of Speed'), include.rownames=F,include.colnames=F, caption.placement="top")
save(Patients,file="./Oswestry_Patients.rData")
